import React, {useState, useEffect} from 'react';
import { useHistory, Redirect } from "react-router-dom";


function ButtonPage () {
    const history = useHistory();
    const [time, setTime] = useState(60)
    const [message, setMessage] = useState('Clock is Ticking')

    const startCount = () => {
       let timer = setTimeout(() => {
            if (time === 0) {
                setMessage('You Failed')
                return history.push('/')
            }
            if (time === 45) {
                setMessage('Plenty of time, relax')
            }
            if (time === 30) {
                setMessage('You OK?')
            }
            if (time === 20){
                setMessage('Better Hurry!')
            }
            if (time === 10){
                setMessage('DO NOT FAIL ME!')
            }
            setTime(time => time - 1)
        }, 500)
    }

useEffect(() => {
    startCount()
}, [time])

    const next = () => {
        history.push('/p111555444333')
    }
  
    return (
        <div>
            <h3>Find the working button</h3>
            <h3>  {message}</h3>
            <h2> {time} </h2>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button>Click Me</button>
            <button onClick={() => next()}>Click Me</button>
            <button>Click Me</button>

        </div>
    )

}


export default ButtonPage;